require "towers_of_hanoi/controller"
require "towers_of_hanoi/board"
require "towers_of_hanoi/game"
require "towers_of_hanoi/move"
require "towers_of_hanoi/view"
require "towers_of_hanoi/board/tower"
require "towers_of_hanoi/board/brick"
require "towers_of_hanoi/board/base"
